### ISSUE TITLE
option for react-16 JSX array (no wrapping div)

### ISSUE THREAD

**Issue by graingert** [mapbox/jsxtreme-markdown#28]
in:
```html
Foo

bar
```

out:
```jsx
[
  <p key="1">Foo</p>
  <p key="2">bar</p>
]
```

**Comment by graingert** [comment]
in:
```
Foo

bar
```

out:
```
[
  <p>Foo</p>
  <p>bar</p>
]
```

**Comment by davidtheclark** [comment]
Ah, interesting ... I guess this would be an option for [toJsx](https://github.com/mapbox/jsxtreme-markdown/tree/master/packages/jsxtreme-markdown#tojsx), which would then make it available to all the higher-level functions. 

The way things currently work, I'm afraid this might end up being more trouble than it's worth, because we'd need to parse the string output of htmltojsx to add a `key` attribute to every top-level element, right?

I've occasionally tinkered with the possibility of switching from htmltojsx to https://github.com/algolia/react-element-to-jsx-string, and with that package's latest release it may have fixed the last blocking bug I know of. I wonder if that would enable the feature you're looking for, @graingert.

**Comment by MathiasSM** [comment]
I simply use `React.Fragment` as a wrapper to avoid polluting the DOM. Not sure if that's what @graingert is asking for.

**Comment by graingert** [comment]
A fragment would do too, it's just that the array form was supported earlier

**Comment by MathiasSM** [comment]
Oh, sorry (I didn't know).

**Comment by graingert** [comment]
@MathiasSM it's because more than one JSX element was impossible before react 16
