### ISSUE TITLE
How to generate JSX with added classNames?

### ISSUE THREAD

**Issue by therise3107** [mapbox/jsxtreme-markdown#42]
Hey, guys, I am trying to use this with webpack 4.1.0 and node 8.9.0. My webpack config is like this
 ```
{
   test: /\.md$/,
    loader: 'babel-loader!@mapbox/jsxtreme-markdown-loader'
}
```
In my component I only want the parsed markdown file to pass it to remark react but I am getting a react component. 
My aim is to add Jss to parsed Jsx for which added className is required.
Thank you in advance

**Comment by davidtheclark** [comment]
@therise3107: :wave: The packages here output JSX and component module (JS) strings, not Markdown strings that you could pass to remark-react. If the Webpack loader were to return just the JSX string (instead of a component module), you wouldn't be able to *use* it at run time, right?

> My aim is to add Jss to parsed Jsx for which added className is required.

I don't think I know exactly what you're going for here. Could you elaborate? 

If your aim is to add a class to the elements generated by your Markdown (e.g. every `<p>` should become `<p className="my-p">`, that's probably something that you could achieve with a rehype plugin.

**Comment by therise3107** [comment]
thank you @davidtheclark for the quick reply. I look into it.
