### ISSUE TITLE
How to include JSXtreme plugin options in .babelrc?

### ISSUE THREAD

**Issue by JeffLuong** [mapbox/jsxtreme-markdown#55]
I'm trying to include the [heading](https://github.com/mapbox/jsxtreme-markdown/tree/master/packages/jsxtreme-markdown#headings) options into my babel build but doesn't seem to be working. There's no `id`s on the resulting HTML headers. Here's what my `.babelrc` file currently looks like:

```
  "plugins": [
    //...other plugins,
    ["@mapbox/babel-plugin-transform-jsxtreme-markdown", { "headings": true } ]
  ]
```

Can anyone please point me in the right direction as to what i'm doing wrong here? Thanks!

**Comment by davidtheclark** [comment]
Hi @JeffLuong. The Babel plugin uses the `toJsx` function, which does not have a `headings` option. `toComponentModule` has the `headings` option. The thinking there is that `headings` would not work with `toJsx` and the Babel plugin because its goal is not just to add IDs to headings but also to create a separate data structure that represents the headings, which you could use in some component to create navigation.

If all you want is to add IDs to heading elements, [remark-slug](https://github.com/remarkjs/remark-slug) should do the trick, which you can integrate with the [`remarkPlugins`](https://github.com/mapbox/jsxtreme-markdown/tree/master/packages/jsxtreme-markdown#remarkplugins) option.

**Comment by JeffLuong** [comment]
Hi @davidtheclark, thanks for pointing that out! A few things regarding `remark-slug` however:

- I installed the `remark-slug`
- included it as a plugin option into my `.babelrc` (see below)
- I'm getting an error that seems to be from an interface between `jsxtreme` and `remark / unified`

### .babelrc file
```
  "plugins": [
    // ...other plugins,
    [
      "@mapbox/babel-plugin-transform-jsxtreme-markdown", {
        "remarkPlugins": ["remark-slug"]
      }
    ]
  ]
```

I'm getting an error thrown on build: `Expect unusable value, not `remark-slug` getting through from [unified js](https://github.com/unifiedjs/unified/blob/master/index.js#L187). It looks like `jsxtreme` is passing in just the string name taken from the `.babelrc` file, and unified is looking for either a function or an object...

Have you noticed / seen this issue before? Thanks in advanced!

**Comment by davidtheclark** [comment]
Hm, the problem is that the string `'remark-slug'` is not how remark plugins are specified: they're specified by pulling in the module, e.g. `remarkPlugins: [require('remark-slug')]`. I know that's going to be a problem with a Babel config file that's not `.js` — maybe you could use `babel.config.js`, which was introduced in Babel 7?

**Comment by JeffLuong** [comment]
Yea I started looking into that - unfortunately we'd have to upgrade our babel to use that...hopefully will not cause any serious breakage when after doing so. Thanks again for the help!
